#!/usr/bin/env  sh
# Depends on location - Xrandr
# xrandr --output DisplayPort-0 --mode 1920x1080 --rate 60 --above "eDP"
xrandr --output DisplayPort-0 --mode 1600x900 --rate 60 --right-of "eDP"
killall -q polybar
while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done

if type "xrandr"; then
  for m in $(xrandr --query | grep " connected" | cut -d" " -f1); do
    MONITOR=$m polybar --reload bar &
  done
else
  polybar --reload bar &
fi
pulseaudio -k || pulseaudio &
~/.fehbg

