#!/usr/bin/env bash

device=11
state=$(xinput list-props "$device" | grep "Device Enabled" | grep -o "[01]$")

if [ $state == '1' ];then
  xinput --disable "$device"
  notify-send "Touchpad Disabled"
else
  xinput --enable "$device"
  notify-send "Touchpad Enabled"
fi
