#!/usr/bin/env bash

width=${2:-100%}
height=${2:-30%}
if [ "$(tmux display-message -p -F "#{session_name}")" = "popup" ];then
    tmux detach-client
else
    # tmux popup -d '#{pane_current_path}' -xC -yC -w$width -h$height -E "tmux attach -t popup || tmux new -s popup"
    tmux popup -d '#{pane_current_path}' -xC -yP -w"$width" -h"$height" -E "tmux attach -t popup || tmux new -s popup"
    # tmux popup -d '#{pane_current_path}' -xC -yP -w"$width" -h"$height" -E "ranger"
fi
