#!/usr/bin/env bash
xinput --map-to-output $(xinput list --id-only "Wacom HID 5203 Pen Pen (0xb746368a)") eDP
xinput --map-to-output $(xinput list --id-only "Wacom HID 5203 Finger") eDP
# notify-send "Xinput Fix"
