add_newline = false

[battery]
full_symbol        = "•"
charging_symbol    = "⇡"
discharging_symbol = "⇣"
format             = "[$symbol$percentage]($style) "

[[battery.display]]
threshold = 30
style     = "bold grey"

[character]
disabled = false
success_symbol = "[»](bold blue)"
error_symbol = "[»](bold red)"
vicmd_symbol = "[»](bold yellow)"

[directory]
style = "bold grey"
truncation_length=2
#fish_style_pwd_dir_length=1

[lua]
disabled = false
symbol = " "
style = "bold blue"
