#!/usr/bin/env bash
if [ $(bluetoothctl show | grep "Powered: yes" | wc -c) -eq 0 ]
then
  echo "  none"
else
  if [ $(echo info | bluetoothctl | grep 'Device' | wc -c) -eq 0 ]
  then
  echo "  disc"
  fi
  echo "  `bluetoothctl devices | awk -F ' ' '{ print $3 }'`"
fi
